coverage:
  precision: 2
  round: down
  range: '80...100'
  status:
    project:
      default:
        enabled: yes
        target: 80%
    patch:
      default:
        enabled: yes
        target: 80%
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  branches:
    - main
