export default function Home() {
  return (
    <div>
      <title>console</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <main>Landing Page</main>

      <footer>Footer</footer>
    </div>
  );
}
