name: Check Size

on:
  push:
    branches: [v1]
  pull_request:
    branches: [v1]

jobs:
  check_size:
    name: Check Size
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
