name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn

      - name: Set Environment Variables
        run: |
          echo "REACT_APP_API_URL=http://localhost:3000" >> $GITHUB_ENV

      - name: Build
        run: |
          cd src
          yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'

      - name: Update code coverage badge
        run: npx update-badge

      - name: Set code coverage commit status 📫
        run: npx -p check-code-coverage set-gh-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure coverage has not dropped 📈
        run: npx -p check-code-coverage set-gh-status --check-against-readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
