name: Lint

on:
  push:
    branches: [v1]
  pull_request:
    branches: [v1]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: lint
        run: yarn lint

      - name: Markdown lint
        uses: docker://avtodev/markdown-lint:v1
